name: Azure Deployment

on:
  push:
    branches:
      - main

# permissions:
#   id-token: write
#   contents: read
      
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install fastapi
        pip install uvicorn
        pip install pandas
        pip install scikit-learn
        pip install httpx
    
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Test backend with pytest
      run: |
        cd backend && pytest

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show
    
    - name: Azure ACR login
      run: |
        az acr login --name paulineregistreb15

    - name: Build and push Docker images
      run: |
        docker build -t back-ajax2-az backend/
        docker build -t front-ajax2-az frontend/
        docker tag back-ajax2-az paulineregistreb15.azurecr.io/pauline-b15-back2
        docker tag front-ajax2-az paulineregistreb15.azurecr.io/pauline-b15-front2
        docker push paulineregistreb15.azurecr.io/pauline-b15-back2
        docker push paulineregistreb15.azurecr.io/pauline-b15-front2
    
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "password.registry"
        replace: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
        regex: false
        include: 'deploy-aci.yaml'
    
    - name: Delete Previous Same Container Instances
      run: az container delete --resource-group pauline-RG-Brief15 --name paulineContainerGroupB15-2 --yes

    - name: Deploy to Azure Container Instances
      run: az container create --resource-group pauline-RG-Brief15 --file deploy-aci.yaml