name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Black
      run: pip install black

    - name: Format code with Black
      run: black .
  
    - name: Authenticate with Azure CLI
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: |
        az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

    - name: Build and push Docker images
      run: |
        docker build -t back-ajax2-az backend/
        docker build -t front-ajax2-az frontend/
        docker tag back-ajax2-az paulineregistreb15.azurecr.io/pauline-b15-back2
        docker tag front-ajax2-az paulineregistreb15.azurecr.io/pauline-b15-front2
        docker push paulineregistreb15.azurecr.io/pauline-b15-back2
        docker push paulineregistreb15.azurecr.io/pauline-b15-front2

    - name: Deploy to Azure Container Instances
      run: az container create --resource-group pauline-RG-Brief15 --file deploy-aci.yaml --registry-username paulineregistreb15
