name: Azure Deployment

on:
  push:
    branches:
      - main

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Black
      run: pip install black

    - name: Format code with Black
      run: black .
  
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show
    
    - name: Azure ACR login
      run: |
        az acr login --name paulineregistreb15
        az acr repository permission add --name paulineregistreb15 --repository pauline-b15-back2 --principal paulineSP --actions read
        az acr repository permission add --name paulineregistreb15 --repository pauline-b15-front2 --principal paulineSP --actions read
      env:
        ACR_USER: paulineregistreb15
        ACR_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t back-ajax2-az backend/
        docker build -t front-ajax2-az frontend/
        docker tag back-ajax2-az paulineregistreb15.azurecr.io/pauline-b15-back2
        docker tag front-ajax2-az paulineregistreb15.azurecr.io/pauline-b15-front2
        docker push paulineregistreb15.azurecr.io/pauline-b15-back2
        docker push paulineregistreb15.azurecr.io/pauline-b15-front2

    - name: Deploy to Azure Container Instances
      run: az container create --resource-group pauline-RG-Brief15 --file deploy-aci.yaml --registry-username paulineregistreb15
