name: Azure Deployment

on:
  push:
    branches:
      - main
# voir pour on quand python test fini et ok
# deploy que on pytest sans erreur

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show
    
    - name: Azure ACR login
      run: |
        az acr login --name paulineregistreb15

    - name: Build and push Docker images
      run: |
        docker build -t back-ajax2-az backend/
        docker build -t front-ajax2-az frontend/
        docker tag back-ajax2-az paulineregistreb15.azurecr.io/pauline-b15-back2
        docker tag front-ajax2-az paulineregistreb15.azurecr.io/pauline-b15-front2
        docker push paulineregistreb15.azurecr.io/pauline-b15-back2
        docker push paulineregistreb15.azurecr.io/pauline-b15-front2
    
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "password.registry"
        replace: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
        regex: false
        include: 'deploy-aci.yaml'
    
    # rajouter une étape delete groupe de container actuel

    - name: Deploy to Azure Container Instances
      # run: az container create --resource-group pauline-RG-Brief15 --file deploy-aci.yaml
      run: az container create --resource-group pauline-RG-Brief15 --file deploy-aci.yaml
    
    # rajouter une notification : liste des commit(avec chaque commit = une tache)
    # bonne pratique commit: {tag du ticket} description